title: 十一城
description: 跬步千里，小流江海。

menu:
  Home: /
  Linux: /categories/linux
  ML: /categories/ml
  Python: /categories/python
  Java: /categories/java
  Thoughts: /thoughts
  KmKg: /kmkg
  BookCan: /bookcan
  Links: /links
  About: /about

rss: /atom.xml

# your name
signoff: dzzxjl

# disqus comment thread for post header options ( leave blank if unwanted )
disqus_shortname: 

# set tracking, UA-XXXX-Y
google_analytics: 
